/// A seeded, reproducible pseudo-random generator: SplitMix64.
///
/// # Why this crate implements its own
///
/// Safeguard S5 requires that every choice a multi-peer scenario makes be
/// reproducible from a seed. A general-purpose RNG crate would satisfy that in
/// principle, but not in practice: its algorithm may change between semver
/// versions, so a recorded trace could stop matching after a `cargo update`
/// with no change to this workspace at all. SplitMix64 is thirty lines, is
/// specified by its constants, and pins the byte-for-byte output of every
/// scenario built on it forever.
///
/// It is deliberately **not** cryptographic and is never used for key
/// material, nonces, or anything an adversary sees — key derivation in this
/// crate feeds real Ed25519, and the seed is a test fixture.
///
/// # Determinism contract
///
/// Two `SeededRng`s built from the same seed produce identical sequences, on
/// every platform and in every build profile. Nothing here reads a clock, an
/// address, or an environment variable.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SeededRng {
    state: u64,
}

impl SeededRng {
    /// The SplitMix64 increment: the odd constant 2^64 / φ.
    const GAMMA: u64 = 0x9E37_79B9_7F4A_7C15;
    const MIX_A: u64 = 0xBF58_476D_1CE4_E5B9;
    const MIX_B: u64 = 0x94D0_49BB_1331_11EB;

    /// FNV-1a 64-bit offset basis and prime, used only to fold a label into a
    /// seed so that named peers get stable, distinct key material.
    const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
    const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

    /// A generator starting from `seed`.
    pub const fn from_seed(seed: u64) -> Self {
        Self { state: seed }
    }

    /// A generator for one named thing inside a seeded run.
    ///
    /// Folding the label in is what makes `alice`'s keypair the same in every
    /// run of a scenario while remaining different from `bob`'s, without the
    /// harness having to hand out indices in a fixed order.
    pub const fn for_label(seed: u64, label: &str) -> Self {
        let mut hash = Self::FNV_OFFSET_BASIS ^ seed;
        let bytes = label.as_bytes();
        let mut index = 0;

        while index < bytes.len() {
            hash ^= bytes[index] as u64;
            hash = hash.wrapping_mul(Self::FNV_PRIME);
            index += 1;
        }

        Self::from_seed(hash)
    }

    /// The next value in the sequence.
    pub const fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(Self::GAMMA);

        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(Self::MIX_A);
        z = (z ^ (z >> 27)).wrapping_mul(Self::MIX_B);
        z ^ (z >> 31)
    }

    /// A value in `0..bound`, uniformly and without modulo bias; `0` when
    /// `bound` is `0`.
    ///
    /// Rejection sampling rather than a bare `%`: a biased draw would make a
    /// scenario's "random" choice quietly favour low indices, which is the kind
    /// of thing that hides a bug rather than finding one. The rejection loop
    /// terminates with probability 1 and, being seeded, always takes the same
    /// number of steps for the same seed.
    pub const fn below(&mut self, bound: u64) -> u64 {
        if bound == 0 {
            return 0;
        }

        // `bound.wrapping_neg() % bound` is `2^64 % bound`: the size of the
        // partial block at the top of the range that must be rejected.
        let zone = bound.wrapping_neg() % bound;

        loop {
            let value = self.next_u64();
            if value >= zone {
                return value % bound;
            }
        }
    }

    /// Fills `out` with generated bytes.
    pub const fn fill_bytes(&mut self, out: &mut [u8]) {
        let mut index = 0;

        while index < out.len() {
            let word = self.next_u64().to_be_bytes();
            let mut byte = 0;

            while byte < word.len() && index < out.len() {
                out[index] = word[byte];
                index += 1;
                byte += 1;
            }
        }
    }

    /// Shuffles `items` in place with a Fisher-Yates pass.
    ///
    /// The one place a scenario's ordering choice becomes visible, so it draws
    /// from this generator and from nowhere else.
    pub fn shuffle<T>(&mut self, items: &mut [T]) {
        if items.len() < 2 {
            return;
        }

        let mut index = items.len() - 1;
        while index > 0 {
            // `index` is at most `usize::MAX`, and the draw is bounded by
            // `index + 1`, so the cast back cannot truncate.
            let swap = self.below(index as u64 + 1) as usize;
            items.swap(index, swap);
            index -= 1;
        }
    }
}
