#!/usr/bin/env python3
"""Regenerate .claude/agents/*.md from .codex/agents/*.toml.

The two tools cannot share a file: Codex reads TOML with a `developer_instructions`
string, Claude Code reads Markdown with YAML frontmatter. This script makes the
Codex definitions the single source of truth and derives the Claude Code
subagents from them.

Two things are added on top of the TOML, both defined here rather than in the
source files:

  * ROUTING — a "use when" clause appended to each description. Codex
    descriptions are terse because the agent is named explicitly; Claude Code
    matches on the description to decide whether to delegate at all, so the
    bare descriptions are too thin to route on.
  * sandbox_mode = "read-only" — has no Claude Code equivalent, so it is
    enforced structurally with a read-only `tools:` list.

Usage:
    scripts/sync-claude-agents.py            # write .claude/agents/*.md
    scripts/sync-claude-agents.py --check    # exit 1 if on-disk files drifted

Requires Python 3.11+ (tomllib).
"""

from __future__ import annotations

import argparse
import difflib
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CODEX_AGENTS = REPO_ROOT / ".codex" / "agents"
CLAUDE_AGENTS = REPO_ROOT / ".claude" / "agents"

MARKER = "<!-- Generated by scripts/sync-claude-agents.py from {source} — edit that file, not this one. -->"
MARKER_PREFIX = "<!-- Generated by scripts/sync-claude-agents.py"

# Tool set standing in for Codex's sandbox_mode = "read-only".
READ_ONLY_TOOLS = "Read, Grep, Glob, WebFetch, WebSearch"

# Claude Code delegates based on the description, so each agent needs a clause
# telling the main loop when to hand work over. Keyed by agent name.
ROUTING = {
    "system-architect": (
        "Use before designing or moving code across contexts, when dependency "
        "direction is unclear, or when a change needs a command/query "
        "classification and contract review."
    ),
    "domain-modeler": (
        "Use when modeling or changing domain concepts, expressing invariants, "
        "or defining port contracts and shared types."
    ),
    "application-handler": (
        "Use when implementing or changing a use case in the application "
        "layer, or composing dependencies for a context."
    ),
    "api-designer": (
        "Use when adding or changing an endpoint, its transport types, status "
        "codes, or error envelope."
    ),
    "repo": (
        "Use when implementing a repository port, changing schema or mappings, "
        "or handling transaction and concurrency behavior."
    ),
    "test-writer": (
        "Use to add missing coverage, build fakes, or reproduce a defect with a "
        "failing test before it is fixed."
    ),
    "spdd-executor": (
        "Use to carry out one assigned canvas operation end to end with TDD and "
        "verification."
    ),
}


class SyncError(Exception):
    """A source file is malformed or inconsistent."""


def yaml_scalar(value: str) -> str:
    """Quote a frontmatter value only when plain style would misparse."""
    risky = ": " in value or value.endswith(":") or value[:1] in "&*!|>%@`'\"[{#-?"
    if not risky:
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(source: Path) -> tuple[str, str]:
    """Return (agent_name, markdown) for one Codex agent definition."""
    data = tomllib.loads(source.read_text(encoding="utf-8"))

    for field in ("name", "description", "developer_instructions"):
        if not str(data.get(field, "")).strip():
            raise SyncError(f"{source.name}: missing required field '{field}'")

    name = data["name"].strip()
    if name != source.stem:
        raise SyncError(
            f"{source.name}: name '{name}' does not match filename '{source.stem}'"
        )

    description = " ".join(data["description"].split())
    hint = ROUTING.get(name)
    if hint:
        description = f"{description} {hint}"
    else:
        print(
            f"warning: no ROUTING entry for '{name}'; Claude Code may not "
            f"delegate to it reliably. Add one in {Path(__file__).name}.",
            file=sys.stderr,
        )

    sandbox = data.get("sandbox_mode")
    if sandbox not in (None, "read-only"):
        raise SyncError(
            f"{source.name}: unhandled sandbox_mode '{sandbox}'; teach "
            f"{Path(__file__).name} how to express it as a tool list"
        )

    lines = [
        "---",
        f"name: {yaml_scalar(name)}",
        f"description: {yaml_scalar(description)}",
    ]
    if sandbox == "read-only":
        lines.append(f"tools: {READ_ONLY_TOOLS}")
    lines += [
        "---",
        "",
        MARKER.format(source=source.relative_to(REPO_ROOT)),
        "",
        data["developer_instructions"].strip(),
        "",
    ]
    return name, "\n".join(lines)


def is_generated(path: Path) -> bool:
    try:
        return MARKER_PREFIX in path.read_text(encoding="utf-8")
    except OSError:
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 instead of writing files",
    )
    args = parser.parse_args()

    if not CODEX_AGENTS.is_dir():
        print(f"error: {CODEX_AGENTS} not found", file=sys.stderr)
        return 2

    sources = sorted(CODEX_AGENTS.glob("*.toml"))
    if not sources:
        print(f"error: no agent definitions in {CODEX_AGENTS}", file=sys.stderr)
        return 2

    try:
        rendered = dict(render(source) for source in sources)
    except (SyncError, tomllib.TOMLDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    CLAUDE_AGENTS.mkdir(parents=True, exist_ok=True)
    drift: list[str] = []
    written = 0

    for name, content in rendered.items():
        target = CLAUDE_AGENTS / f"{name}.md"
        current = target.read_text(encoding="utf-8") if target.exists() else None

        if current == content:
            continue

        if args.check:
            diff = difflib.unified_diff(
                (current or "").splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"{target.relative_to(REPO_ROOT)} (on disk)",
                tofile=f"{target.relative_to(REPO_ROOT)} (expected)",
            )
            label = "missing" if current is None else "stale"
            drift.append(f"{label}: {target.relative_to(REPO_ROOT)}\n" + "".join(diff))
        else:
            target.write_text(content, encoding="utf-8")
            written += 1

    # A generated .md whose .toml source disappeared is drift too. Only files
    # carrying our marker are ours to remove; anything hand-written is left alone.
    for stale in sorted(CLAUDE_AGENTS.glob("*.md")):
        if stale.stem in rendered:
            continue
        rel = stale.relative_to(REPO_ROOT)
        if not is_generated(stale):
            print(f"note: {rel} is hand-written, not generated; leaving it alone.")
            continue
        if args.check:
            drift.append(f"orphaned: {rel} has no .codex/agents/{stale.stem}.toml\n")
        else:
            stale.unlink()
            print(f"removed {rel} (source .toml is gone)")

    if args.check:
        if drift:
            print("\n".join(drift), file=sys.stderr)
            print(
                f"\n{len(drift)} agent file(s) out of sync with .codex/agents/. "
                f"Run scripts/{Path(__file__).name} to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"{len(rendered)} agent file(s) in sync with .codex/agents/.")
        return 0

    print(
        f"{len(rendered)} agent(s) generated from .codex/agents/ "
        f"({written} changed)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
